Fix current site bugs
kartoza/africa_rangeland_watch pull request #142
Opened 2024-11-28 13:26 UTC by tinashechiraya

this is linked to issue

[Screencast from 2024-11-28 15-13-33.webm](https://github.com/user-attachments/assets/be76fca2-3b66-4daa-8126-2e7269a7f597)

2024-11-29 15:29 UTC, dimasciput requested changes

2024-11-29 15:29 UTC, dimasciput commented on django_project/frontend/src/store/ticketSlice.ts
> +const setCSRFToken = () => {
Can you put this function in the utils instead? Remember to follow the DRY approach.

2024-12-02 09:37 UTC, dimasciput commented on django_project/frontend/src/store/ticketSlice.ts
> +      setCSRFToken();
import from csrfUtils instead

2024-12-03 08:47 UTC, tinashechiraya commented on django_project/frontend/src/store/ticketSlice.ts
> +      setCSRFToken();
resolved @dimasciput

2024-12-03 09:51 UTC, merged