Implement session continuity
kartoza/africa_rangeland_watch pull request #201
Opened 2024-12-18 00:09 UTC by tinashechiraya

this is linked to issue:

[Screencast from 2024-12-18 01-54-26.webm](https://github.com/user-attachments/assets/719d3de4-116b-488c-bcea-354a06293fd8)

2025-01-15 07:29 UTC, tinashechiraya commented
also resolved https://github.com/kartoza/africa_rangeland_watch/issues/227

2025-01-15 15:29 UTC, dimasciput requested changes
@tinashechiraya Please update your PR, there are so many unrelated changes with the current ticket.

2025-01-15 15:29 UTC, dimasciput commented on django_project/core/settings/prod.py
> +EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
Why use console?

2025-01-15 15:29 UTC, dimasciput commented on django_project/base/templates/ARW_Admin has made you Organisation Manager.html
> +<!DOCTYPE html>
This is unrelated with current PR

2025-01-15 15:29 UTC, dimasciput commented on django_project/base/templates/approve_add_organization.html
> +{% extends "admin/base_site.html" %}
Unrelated

2025-01-16 17:35 UTC, tinashechiraya commented
I will dissolve this pr into multiple ones then close it @dimasciput

2025-01-29 07:00 UTC, tinashechiraya commented
all the prs for this task have been merged

2025-01-29 07:00 UTC, closed without merging